name: Deploy via FTP (Locaweb) # v2

on:
  push:
    branches: [ "main" ]
    paths:
      - "public_html/**"
      - ".github/workflows/main.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: FTP Deploy Locaweb
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          local-dir: ./public_html/
          server-dir: ./public_html/
          dangerous-clean-slate: true
